image: docker:latest

services:
  - docker:dind

variables:
  # Define your DockerHub repository and image name here
  DOCKER_IMAGE: "anbudo2/iti0302-2024-backend"

stages:
  - build
  - push
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    # Build the Docker image from the Dockerfile in the current directory
    - docker build -t "$DOCKER_IMAGE" .
    # Tag the Docker image with the current commit SHA for versioning
    - docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE:$(echo $CI_COMMIT_SHA)"

push:
  stage: push
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    # Push the Docker image to DockerHub
    - docker push "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHA"

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "cd /home/ubuntu && docker-compose down && docker-compose pull && docker-compose up -d --remove-orphans"

only:
  - main