version: "3.8"
services:
  postgres:
    container_name: iti0302-2024-backend-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bestuser