version: "3.8"
services:
  backend:
    build: .
    container_name: iti0302-2024-backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: iti0302-2024-backend-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
