version: "3.8"
services:
  backend:
    build: .
    container_name: iti0302-2024-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: iti0302-2024-backend-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bestuser