spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: iti0302-2024-backend
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml
    drop-first: ${DEBUG}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}


security:
  jwt:
    access: 1
    refresh: 1
    secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: trace

#server:
#  port: 8083
